import {
    AlertTriangle,
    ArrowRight,
    Check,
    Menu,
    ChevronLeft,
    ChevronRight,
    FileSpreadsheet,
    CreditCard,
    File,
    FileText,
    HelpCircle,
    Image,
    Laptop,
    Loader2,
    LucideProps,
    LogIn,
    Moon,
    MoreVertical,
    Pizza,
    Plus,
    Settings,
    SunMedium,
    Trash,
    Twitter,
    User,
    X,
    LucideIcon,
    LayoutDashboard,
    Github,
    Mail,
    Shell,
    SendHorizonal,
    Tally2,
    AlignJustify,
    AtSign,
    CalendarDays,
    Clock,
    Phone,
    Link,
    HashIcon,
    Equal,
    PenSquare,
    Copy,
    ExternalLink,
    Trash2,
  } from "lucide-react"
  

  export type Icon = LucideIcon
  
  export const Icons = {
    logo:Shell,
    form: FileSpreadsheet,
    close: X,
    dashboard:LayoutDashboard,
    spinner: Loader2,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    trash: Trash2,
    post: FileText,
    page: File,
    media: Image,
    settings: Settings,
    billing: CreditCard,
    ellipsis: MoreVertical,
    add: Plus,
    warning: AlertTriangle,
    user: User,
    arrowRight: ArrowRight,
    help: HelpCircle,
    pizza: Pizza,
    menu:Menu,
    sun: SunMedium,
    moon: Moon,
    laptop: Laptop,
    twitter: Twitter,
    check: Check,
    login:LogIn,
    gitHub:Github,
    mail:Mail,
    submit:SendHorizonal,
    shortText:Equal,
    longText:AlignJustify,
    email:AtSign,
    date:CalendarDays,
    time:Clock,
    phone:Phone,
    number:HashIcon,
    link:Link,
    edit:PenSquare,
    copy:Copy,
    externalLink:ExternalLink
  }
  
    