import {
    AlertTriangle,
    ArrowRight,
    Check,
    Menu,
    ChevronLeft,
    ChevronRight,
    FileSpreadsheet,
    CreditCard,
    File,
    FileText,
    HelpCircle,
    Image,
    Laptop,
    Loader2,
    LucideProps,
    LogIn,
    Moon,
    MoreVertical,
    Pizza,
    Plus,
    Settings,
    SunMedium,
    Trash,
    Twitter,
    User,
    X,
    LucideIcon,
    LayoutDashboard,
  } from "lucide-react"
  

  export type Icon = LucideIcon
  
  export const Icons = {
    logo: FileSpreadsheet,
    close: X,
    dashboard:LayoutDashboard,
    spinner: Loader2,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    trash: Trash,
    post: FileText,
    page: File,
    media: Image,
    settings: Settings,
    billing: CreditCard,
    ellipsis: MoreVertical,
    add: Plus,
    warning: AlertTriangle,
    user: User,
    arrowRight: ArrowRight,
    help: HelpCircle,
    pizza: Pizza,
    menu:Menu,
    sun: SunMedium,
    moon: Moon,
    laptop: Laptop,
    twitter: Twitter,
    check: Check,
    login:LogIn
  }
  
    